### ISSUE TITLE
Tether questions

### ISSUE THREAD

**Issue by SatWiz** [dart-bridge/dart-bridge.github.io#5] opened 2015-08-28 10:34 UTC
Hi, I would like to know more about Tether. I see a couple examples about tether triggered by client side code. But I would like to use tether to send an object to client side triggered from a router handling.
## I have this snippet in the router part:

```
router.get('/live/data/:record', (shelf.Request request, {String record}) async {
  var result = await getSomeData(record);
  if (await result == null) throw new HttpNotFoundException(request);
  // now I would like to send the record to client side for further processing
  tether(Tether tether) {
    tether.send('data_struct', result);
  }
  return template('mytemplate');
});
```

---

Questions:
Can I use tether this way (beside de-/serializing part) to send to client side? If not how to?
Can you give example how to handle/listen at client side in main.dart? 

I see that I can use return template withData to html pages directly but that will not work if I parsed complex objects to Polymer pages for handling.

Thanks for helping me out!

**Comment by emilniklas** [comment] 2015-08-28 12:52
Okay. This is kind of a complex topic, since the Tether only starts working after the client has received the response and connected back. And the server handles multiple tethers, whereas the client only handles one. So there is a manager in the backend: `TetherManager`. You can inject that to access _the collection of tethers_ currently connected, as well as register handlers.

In your example, though, since the tether for the client isn't available at this point, we have to store an identifier in the response, so that the tether can fetch the information as soon as it has connected:

``` dart
class Api {
  final manager = SomeStuffManager();

  routes(Router router) {
    router.get('path', () {
      int id;
      // do stuff
      manager.setSomethingWithId(stuff, id);
      return template('some', withData: {'fetchSomeStuffId': id});
    });
  }

  tether(Tether tether) {
    tether.listen('fetchSomeStuff', (int id) {
      return manager.getSomethingWithId(id);
    });
  }
}
```

On the other hand, if you wanted to broadcast something to every connected session, you could just inject the `TetherManager`:

``` dart
router.get('path', (TetherManager tethers) {
  tethers.broadcast('some_key', 'some_value');
  // equivalent of doing tether.send('some_key', 'some_value'); on every tether
});
```

I'm going to keep this issue open since I think this could be streamlined more. Also it needs more documentation.

Good luck!

**Comment by SatWiz** [comment] 2015-08-28 16:10
Thanks Emil for your explanation, I am a little bit wiser :).

I thought I can send back the complex object in the router handling because I already have the id there from the url part. And can handle it with one database getSomeData() call. 
I will try your first example above if I can achieve the same.

**Comment by SatWiz** [comment] 2015-08-28 23:05
I was just wondering how maps passed in the template are picked up in dart at client side and send back with tether to the server?
Like:
return template('some', withData: {'fetchSomeStuffId': id});

How can id be picked up and send back to the server? I can't find an example in the docs about that. Can you point me to the right direction?

**Comment by emilniklas** [comment] 2015-08-29 07:20
Well, that would be something like this:

``` html
<head>
  <meta name='someStuffId' content='$id'>
</head>
```

And then fetch that through DOM at the client.

Of course, a more convenient approach would be if you could do the entire "stuff" after the page has loaded.

**Comment by SatWiz** [comment] 2015-08-29 08:46
I mean how to get id in dart client code ;) I understand it is parsed to client html but need processing in dart code.

**Comment by SatWiz** [comment] 2015-08-29 09:32
btw how can I check at server side if there is a tether client connected?

**Comment by emilniklas** [comment] 2015-08-29 12:32
``` dart
import 'dart:html';
main() {
  // something like this
  querySelector('meta[name=someStuffId]').getAttribute('content');
}
```

Whole process:
- Request comes in
- Perform some action generate an identifier
- Send the identifier to the client
- In client code, after `globalTether()`, fetch the id from DOM
- Use the client tether to request something from the server, passing through the id
- Let the server receive the id and it now knows what http request generated this tether connection

Remember that all sessions are connected to the same running Dart process. So you shouldn't check for connected tethers because that is very dependent on a state in time. I'm looking at ways to use the `Session` class for these kinds of situations. Something might come up soon.

**Comment by SatWiz** [comment] 2015-08-29 15:04
ok, understand that but is not a nice solution as it looks like a 3 steps rocket. Hopefully you can do some passing directly in the future.

Other issue I have now is although I return template('template', withScript: 'main'); 
It seems main script in /web/main.dart is never executed. Did I missed some registration of the script?

**Comment by emilniklas** [comment] 2015-08-29 15:25
That shouldn't be any problem. Can you see any error messages in the console of Dartium? If not, do you see any script tag in the source code of your page at all?

**Comment by SatWiz** [comment] 2015-08-29 17:17
no errors at all. As test I only wrote something to the console log. Either print and window.console.info don't write anything to browser console from main.dart. 

correction: it is written to console within chromium and not to chrome. I think it is as designed?

**Comment by SatWiz** [comment] 2015-08-29 19:10
stupid me off course it is as designed :) Need to find out dough how pub serve can change port to 1337 for bridge.

**Comment by emilniklas** [comment] 2015-08-31 09:40
It _is_ as designed, but it's not up to pub serve. Here's what's up:

Bridge uses environment variables to determine the environment in which it's being run. So for example, it looks for a variable called `APP_ENV` and expects either `production`, `development` or other ones (which will be interpreted as `development` internally).

To simplify the environment variable situation, Bridge uses "dotenv", a standard where a file called `.env` is located in the root of the project. That file can contain environment variable assignments and not be included in version control (Git). That means you can have a `.env` file on your local machine with `APP_ENV=development`, and another on your production server with `APP_ENV=production`. However, you don't need to, because if there is no `.env`, production mode will be the default. This way you can share codebase and deploy with Git without having to change things on the public server.

If it sees that it's in a development environment, it will assume that you're using Dartium (Chromium) to see the application. Therefore, it will turn `template('template' withScript: 'main')` into a template with a script tag like so: `<script type='application/dart' src='main.dart'></script>`

If you want to see the app running in other browsers, you will have to do two things:
- Change into production mode (change the contents of `.env` to `APP_ENV=production`)
- Run the `build` command (`= build`)

The build command will use `dart2js` to turn `main.dart` into `main.dart.js`. The production mode will output `<script src='main.dart.js'></script>` instead of the Dart script tag.

**Comment by emilniklas** [comment] 2015-09-29 16:00
This is being tracked [here](https://github.com/dart-bridge/framework/issues/32).

**Closed as completed by emilniklas** 2015-09-29 16:00 UTC
